BanHangDienTu/Models/khachhang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khachhang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khachhang()
        {
            this.giohangs = new HashSet<giohang>();
            this.hoadons = new HashSet<hoadon>();
        }
    
        public int khachhang_id { get; set; }
        public string khachhang_ten { get; set; }
        public System.DateTime khachhang_ngaysinh { get; set; }
        public string khachhang_sdt { get; set; }
        public string khachhang_diachi { get; set; }
        public string khachhang_email { get; set; }
        public string khachhang_matkhau { get; set; }
        public int trangthai_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hoadon> hoadons { get; set; }
        public virtual trangthai trangthai { get; set; }
    }
}

BanHangDienTu/Controllers/KhachHangController.cs
using BanHangDienTu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHangDienTu.Controllers
{
    public class KhachHangController : Controller
    {
        KhachHangModel khModel = new KhachHangModel();
        public ActionResult Login()
        {
            ViewBag.Message = TempData["message"];

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(khachhang model)
        {

            if (ModelState.IsValid)
            {
                var data = khModel.DangNhap(model);
                if (data.Count() > 0)
                {
                    //add session
                    Session["MaKH"] = data.FirstOrDefault().khachhang_id;
                    Session["TenKH"] = data.FirstOrDefault().khachhang_ten;
                    return Redirect("/SanPham/Index");

                }
                else
                {
                    TempData["message"] = "Tên đăng hoặc mật khẩu không chính xác.";
                    ViewBag.mes = "Tên đăng nhập hoặc mật khẩu không chính xác.";
                    return RedirectToAction("Login");
                }
            }
            return View();
        }

        public ActionResult DangKy()
        {
            ViewBag.Message = TempData["message"];

            return View();
        }
        [HttpPost]
        public ActionResult DangKy(khachhang kh)
        {
            var data = khModel.DangKy(kh);
            Session["MaKH"] = data.FirstOrDefault().khachhang_id;
            Session["TenKH"] = data.FirstOrDefault().khachhang_ten;
            TempData["ThemThanhCong"] = "Thêm thành công.";
            return RedirectToAction("Index", "SanPham");

        }
        //Logout
        public ActionResult DangXuat()
        {
            Session.Clear();//remove session
            return RedirectToAction("Index", "SanPham");
        }
    }
}

BanHangDienTu/Views/KhachHang/DangKy.cshtml
@model BanHangDienTu.Models.khachhang

@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Shared/_LayoutDangKyDangNhap.cshtml";
}

<div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                <div class="col-lg-7">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Tạo mới tài khoản</h1>
                        </div>
                        @using (Html.BeginForm("DangKy", "KhachHang", FormMethod.Post, new { @class = "user" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="text" class="form-control form-control-user" id="exampleFirstName" name="khachhang_ten"
                                           placeholder="Nhập tên của bạn" required pattern="\S+.*">
                                </div>
                                <div class="col-sm-6">
                                    <input type="date" class="form-control form-control-user" id="exampleLastName" name="khachhang_ngaysinh" required pattern="\S+.*">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control form-control-user" name="khachhang_diachi" id="exampleInputEmail"
                                       placeholder="Nhập địa chỉ của bạn" required pattern="\S+.*">
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control form-control-user" name="khachhang_email" id="exampleInputEmail"
                                       placeholder="Nhập Email của bạn" required pattern="\S+.*">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <input type="number" class="form-control form-control-user" min="0"
                                           id="exampleInputPassword" placeholder="Số điện thoại" name="khachhang_sdt" required pattern="\S+.*">
                                </div>
                                <div class="col-sm-6">
                                    <input type="password" class="form-control form-control-user"
                                           id="exampleRepeatPassword" placeholder="Mật khẩu" name="khachhang_matkhau" required pattern="\S+.*">
                                </div>
                            </div>
                            <input type="number" value="1" name="trangthai_id" class="hide" />
                            <button type="submit" href="login.html" class="btn btn-primary btn-user btn-block">
                                Đăng ký
                            </button>
                            
                            }
                            <hr>
                            <div class="text-center">
                                <a class="small" href="forgot-password.html">Quên mật khẩu?</a>
                            </div>
                            <div class="text-center">
                                <a class="small" href="@Url.Action("Login","KhachHang")">Bạn đã có tài khoản? Đăng nhập ngay!</a>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

</div>

BanHangDienTu/Views/KhachHang/Login.cshtml
@model BanHangDienTu.Models.khachhang
@{
    ViewBag.Title = "ChiTietSanPham";
    Layout = "~/Views/Shared/_LayoutDangKyDangNhap.cshtml";
}
<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                @using (Html.BeginForm("Login", "KhachHang", FormMethod.Post, new { @class = "user" }))
                                {
                                    @Html.AntiForgeryToken()

                                    
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                   id="exampleInputEmail" aria-describedby="emailHelp"
                                                   placeholder="Enter Email Address..." name="khachhang_email" >
                                        </div>
                                        <div class="form-group">
                                            <input type="password" class="form-control form-control-user"
                                                   id="exampleInputPassword" placeholder="Password" name="khachhang_matkhau" >
                                        </div>
                                        <div class="form-group">
                                            <div class="custom-control custom-checkbox small">
                                                <input type="checkbox" class="custom-control-input" id="customCheck">
                                                <label class="custom-control-label" for="customCheck">
                                                    Remember
                                                    Me
                                                </label>
                                            </div>
                                        </div>
                                        
                                        <input type="submit" name="submit" class="btn btn-primary btn-lg btn-block" value="Login" />
                                        <hr>
                                        <a href="index.html" class="btn btn-google btn-user btn-block">
                                            <i class="fab fa-google fa-fw"></i> Login with Google
                                        </a>
                                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                        </a>
                                    
                                }
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="forgot-password.html">Forgot Password?</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>