BanHangDienTu/Models/loaisanpham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class loaisanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public loaisanpham()
        {
            this.sanphams = new HashSet<sanpham>();
        }
    
        public int loaisanpham_id { get; set; }
        public string loaisanpham_ten { get; set; }
        public int trangthai_id { get; set; }
    
        public virtual trangthai trangthai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}

BanHangDienTu/Models/sanpham.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHangDienTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanpham()
        {
            this.chitiethoadons = new HashSet<chitiethoadon>();
            this.chitietphieunhaphangs = new HashSet<chitietphieunhaphang>();
            this.giohangs = new HashSet<giohang>();
        }
    
        public int sanpham_id { get; set; }
        public string sanpham_ten { get; set; }
        public string sanpham_mota { get; set; }
        public int loaisanpham_id { get; set; }
        public int sanpham_soluong { get; set; }
        public double sanpham_dongia { get; set; }
        public string sanpham_urlhinhanh { get; set; }
        public int trangthai_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitiethoadon> chitiethoadons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietphieunhaphang> chitietphieunhaphangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<giohang> giohangs { get; set; }
        public virtual loaisanpham loaisanpham { get; set; }
        public virtual trangthai trangthai { get; set; }
    }
}

BanHangDienTu/Controllers/SanPhamController.cs
using BanHangDienTu.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanHangDienTu.Controllers
{
    public class SanPhamController : Controller
    {
        SanPhamModel spModel = new SanPhamModel();
        KhachHangModel khModel = new KhachHangModel();
        // GET: SanPham
        public ActionResult Index()
        {

            ViewBag.DS = spModel.DanhSachSP();
            return View();
        }
        public ActionResult ChiTietSanPham(int id)
        {
            ViewBag.ChiTiet = spModel.SanPhamId(id);
            return View(spModel.SanPhamId(id));
        }
        public ActionResult XemGioHang()
        {
            //int idKH = 3;
            int idKH = Int32.Parse(Session["MaKH"].ToString());
            ViewBag.XemGioHang = spModel.XemGioHang(idKH);
            return View();
        }
        public ActionResult ThemGioHang(int id, int sl)
        {

            sanpham sp = spModel.SanPhamId(id);
            int idKH = Int32.Parse(Session["MaKH"].ToString());
            //int idKH = 3;
            giohang gh = new giohang();
            gh.khachhang_id = idKH;
            gh.sanpham_id = id;
            gh.giohang_dongia = sp.sanpham_dongia;

            var kt = spModel.KiemTraSanPhamGioHang(idKH, id);
            if (kt.Count() == 0)
            {
                gh.giohang_soluong = sl;
                spModel.ThemGioHang(gh);
            }
            else
            {
                foreach (var item in kt)
                {
                    gh.giohang_id = item.giohang_id;
                    gh.giohang_soluong = sl + item.giohang_soluong;
                    spModel.SuaGioHang(gh);
                }
            }
            TempData["ThemThanhCong"] = "Thêm thành công.";
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
        }
        public ActionResult CapNhatSoLuong(int id, int sl)
        {
            giohang gh = new giohang();
            var layGH = spModel.GioHangId(id);
            foreach (var item in layGH)
            {
                gh.giohang_id = id;
                gh.khachhang_id = item.khachhang_id;
                gh.sanpham_id = item.sanpham_id;
                gh.giohang_soluong = sl;
                gh.giohang_dongia = item.giohang_dongia;
                break;
            }
            spModel.SuaGioHang(gh);
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
        }
        public ActionResult XoaGioHang(int id)
        {
            spModel.XoaGioHang(id);
            TempData["XoaThanhCong"] = "Xóa thành công.";
            return Redirect(Request.UrlReferrer.ToString());//load lại trang
        }
        public ActionResult ThanhToan()
        {
            //int idKH = 3;
            int idKH = Int32.Parse(Session["MaKH"].ToString());
            ViewBag.SanPham = spModel.XemGioHang(idKH);
            return View(khModel.KhachHangId(idKH));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult XacNhanThanhToan(phieugiaohang pgh)//String phieugiaohang_tennguoinhan, int phieugiaohang_sdtnguoinhan, String phieugiaohang_diachinguoinhan
        {
            int idKH = Int32.Parse(Session["MaKH"].ToString());
            hoadon hd = new hoadon();
            hd.khachhang_id = idKH;
            hd.hoadon_ngaylap = DateTime.Now;
            hd.trangthaihoadon_id = 1;
            int idHD = spModel.ThemHoaDon(hd);//lấy id hóa đơn vừa thêm

            chitiethoadon ct = new chitiethoadon();
            var gh = spModel.XemGioHang(idKH);

            double tongtienHD = 0;//tính tổng tiền của hóa đơn để tiến hành update bảng hóa đơn
            foreach (var item in gh)
            {
                ct.hoadon_id = idHD;
                ct.sanpham_id = item.sanpham_id;
                ct.chitiethd_soluong = item.giohang_soluong;
                ct.chitiethd_thanhtien = item.giohang_soluong * item.giohang_dongia;
                spModel.ThemCTHoaDon(ct);
                tongtienHD = tongtienHD + ct.chitiethd_thanhtien;
            }

            hd.hoadon_tongtien = tongtienHD;
            spModel.SuaHoaDon(hd);

            foreach (var item in gh)
            {
                spModel.XoaGioHang(item.giohang_id);
                spModel.CapNhatSoLuongSP(item.sanpham_id, item.giohang_soluong);
            }

            phieugiaohang pgh1 = new phieugiaohang();
            pgh1.hoadon_id = idHD;
            pgh1.phieugiaohang_tennguoinhan = pgh.phieugiaohang_tennguoinhan;
            pgh1.phieugiaohang_sdtnguoinhan = pgh.phieugiaohang_sdtnguoinhan;
            pgh1.phieugiaohang_diachinguoinhan = pgh.phieugiaohang_diachinguoinhan;
            pgh1.phieugiaohang_thoigiangiaohang = DateTime.Now;
            spModel.ThemPhieuGiaoHang(pgh1);
            
            return RedirectToAction("Index");
        }
        public ActionResult LoaiSanPham(int idTheLoai, int? page = 0)
        {
            ViewBag.IdTheLoai = idTheLoai;
            int limit = 8;
            int start;
            if(page > 0)
            {
                page = page;
            }
            else
            {
                page = 1;
            }
            start = (int)(page - 1) * limit;
            ViewBag.pageCurrent = page;

            int totalProduct = spModel.TongLoaiSanPham(idTheLoai);
            ViewBag.totalProduct = totalProduct;

            ViewBag.numberPage = spModel.numberPage(totalProduct, limit);
            var data =  spModel.LoaiSanPham(idTheLoai, start, limit);
            ViewBag.Model = data;
            
            return View(data);
        }
        public ActionResult DonHangDaDat()
        {
            //int idKH = 3;
            int idKH = Int32.Parse(Session["MaKH"].ToString());
            ViewBag.HD = spModel.LayHoaDon(idKH);
            ViewBag.ChiTietHD = spModel.DonHangDaDat(idKH);
            
            return View();
        }
    }
}

BanHangDienTu/Views/SanPham/DonHangDaDat.cshtml
@model BanHangDienTu.Models.chitiethoadon

@{
    ViewBag.Title = "DonHangDaDat";
    Layout = "~/Views/Shared/_LayoutCustomize.cshtml";
}
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Đơn hàng đã đặt</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="@Url.Action("XemGioHang","SanPham")">Quay lại giỏ hàng</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="col-sm-6 col-lg-6 offset-3 mb-3">
    <div class="row">
        <div class="table-main table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Mã đơn hàng</th>
                        <th>Ngày đặt hàng</th>
                        <th>Tổng tiền(VNĐ)</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>

    </div>
</div>
@{ int s = 1;}
@foreach (var hd in ViewBag.HD)
{
    
    <div class="col-sm-6 col-lg-6 offset-3 mb-3">
        <div class="row">

            <div class="col-md-12 col-lg-12">
                <div class="list-group list-group-collapse list-group-sm list-group-tree" id="list-group-men" data-children=".sub-men">
                    <div class="list-group-collapse sub-men">

                        <a class="list-group-item list-group-item-action" href="#@s" data-toggle="collapse" aria-expanded="false" aria-controls="sub-men2">
                            <div class="row">
                                <span class="col-sm-4"> @hd.hoadon_id</span><span class="col-sm-4">@hd.hoadon_ngaylap</span><span class="col-sm-4">@hd.hoadon_tongtien</span>
                                <small class="text-muted"></small>
                            </div>
                        </a>

                        <div class="collapse" id="@s" data-parent="#list-group-men">
                            <div class="table-main table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr style="background-color:#009966">
                                            <th>Hình ảnh</th>
                                            <th>Tên sản phẩm</th>
                                            <th>Số lượng</th>
                                            <th>Thành tiền</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in ViewBag.ChiTietHD)
                                        {


                                            if (item.hoadon_id == hd.hoadon_id)
                                            {

                                                <tr>
                                                    <td class="thumbnail-img">
                                                        <a href="@Url.Action("ChiTietSanPham","SanPham", new { id = item.sanpham.sanpham_id } )">
                                                            <img class="img-fluid" src="/asset/images/@item.sanpham.sanpham_urlhinhanh" alt="" />
                                                        </a>
                                                    </td>
                                                    <td class="name-pr">
                                                        <a href="@Url.Action("ChiTietSanPham","SanPham", new { id = item.sanpham.sanpham_id } )">
                                                            @item.sanpham.sanpham_ten
                                                        </a>
                                                    </td>
                                                    <td class="price-pr">
                                                        <p>@item.chitiethd_soluong</p>
                                                    </td>
                                                    <td class="total-pr">
                                                        <p>@item.chitiethd_thanhtien</p>
                                                    </td>
                                                </tr>
                                            }

                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    s++;
}

<!-- End Shop Page -->

BanHangDienTu/Views/SanPham/Index.cshtml
@model IEnumerable<BanHangDienTu.Models.sanpham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutCustomize.cshtml";
}
<!-- Start Slider -->
<div id="slides-shop" class="cover-slides">
    <ul class="slides-container">
        <li class="text-center">
            <img src="~/asset/images/nen1.png" alt="">
            
        </li>
        <li class="text-center">
            <img src="~/asset/images/nen2.png" alt="">
            
        </li>
        <li class="text-center">
            <img src="~/asset/images/nen3.png" alt="">
            
        </li>
    </ul>
    <div class="slides-navigation">
        <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
        <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    </div>
</div>
<!-- End Slider -->

<div class="products-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-all text-center">
                    <h1>Sản phẩm nổi bậc</h1>
                    <p>Cùng trải nghiệm các sản phẩm đọc quyền đến từ cửa hàng.</p>
                </div>
            </div>
        </div>
        <div class="row special-list">
            @foreach (var item in ViewBag.DS)
            {
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover" style="height:280px; ">
                            <div class="type-lb">
                                
                            </div>
                            <a href="@Url.Action("ChiTietSanPham","SanPham", new { id = item.sanpham_id } )"><img src="~/asset/images/@item.sanpham_urlhinhanh" class="img-fluid" alt="Image"></a>
                            
                        </div>
                        <div class="why-text">
                            <h4>@item.sanpham_ten</h4>
                            <h5> @String.Format("{0:0,0}", item.sanpham_dongia) VNĐ</h5>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

BanHangDienTu/Views/SanPham/LoaiSanPham.cshtml
@model IEnumerable<BanHangDienTu.Models.sanpham>

@{
    ViewBag.Title = "LoaiSanPham";
    Layout = "~/Views/Shared/_LayoutCustomize.cshtml";
}

<div class="products-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-all text-center">
                    @foreach (var item in ViewBag.Model)
                    {
                        <h1>@item.loaisanpham.loaisanpham_ten</h1>
                        break;
                    }
                    <p>Cùng trải nghiệm các sản phẩm đọc quyền đến từ cửa hàng.</p>
                </div>
            </div>
        </div>
        <div class="row special-list">
            @foreach (var item in ViewBag.Model)
            {
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover" style="height:250px; ">
                            <div class="type-lb">

                            </div>
                            <a href="@Url.Action("ChiTietSanPham","SanPham", new { id = item.sanpham_id } )"><img src="~/asset/images/@item.sanpham_urlhinhanh" class="img-fluid" alt="Image"></a>

                        </div>
                        <div class="why-text">
                            <h4>@item.sanpham_ten</h4>
                            <h5> @String.Format("{0:0,0}", item.sanpham_dongia) VNĐ</h5>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="col-4 offset-9">
        <ul class="pagination">
            @{
                int idTheLoai = ViewBag.IdTheLoai;
                int numberPage = ViewBag.numberPage;
                int pageCurrent = ViewBag.pageCurrent;
                int offset = 8;//number display page

                //<li>@numberPage tong</li>
                //config FirstLink
                if (pageCurrent > 1)
                {
                    int prevPage = pageCurrent - 1;
                    var PrevLink = new Dictionary<string, string> { { "page", prevPage.ToString() } };
                    //<li><a asp-controller="Product" asp-action="Index" asp-all-route-data="PrevLink">Prev Link</a></li>
                    <a href="@Url.Action("LoaiSanPham","SanPham", new { idTheLoai= idTheLoai, page = prevPage})"><li class="btn hvr-hover" style="color:white">Prev Link</li></a>
                }

                int from = pageCurrent - offset;
                int to = pageCurrent + offset;
                if (from <= 0)
                {
                    from = 1;
                    to = offset * 2;
                }


                if (to > numberPage)
                {
                    to = numberPage;
                }

                int i;
                for (i = from; i <= to; i++)
                {

                    if (pageCurrent == i)
                    {
                        //<li class="active"><a asp-controller="SanPham" asp-action="LoaiSanPham" asp-all-route-data="parms">@i</a></li>
                        <a href="@Url.Action("LoaiSanPham","SanPham", new { idTheLoai= idTheLoai, page = @i})"><li class="btn hvr-hover" style="background-color:orangered; color:white">@i</li></a>
                    }
                    else
                    {
                        //<li><a asp-controller="SanPham" asp-action="LoaiSanPham" asp-all-route-data="parms">@i</a></li>
                        <a href="@Url.Action("LoaiSanPham","SanPham", new { idTheLoai= idTheLoai, page = @i})"><li class="btn hvr-hover" style="color:white">@i</li></a>
                    }

                }

                if (pageCurrent < numberPage - (to / 2))
                {
                    <li><a>...</a></li>
                    var LastLink = new Dictionary<string, string> { { "page", numberPage.ToString() } };
                    //<li><a asp-controller="SanPham" asp-action="LoaiSanPham" asp-all-route-data="LastLink">Last Link</a></li>
                    <a href="@Url.Action("LoaiSanPham","SanPham", new { idTheLoai= idTheLoai, page = LastLink})"><li class="btn hvr-hover" style="color:white">Last Link</li></a>
                }

                if (pageCurrent < numberPage)
                {
                    int nextPage = pageCurrent + 1;
                    var NextLink = new Dictionary<string, string> { { "page", nextPage.ToString() } };
                    //<li><a asp-controller="SanPham" asp-action="LoaiSanPham" asp-all-route-data="NextLink">Next Link</a></li>
                    <a href="@Url.Action("LoaiSanPham","SanPham", new { idTheLoai= idTheLoai, page = nextPage})"><li class="btn hvr-hover" style="color:white">Next Link</li></a>
                }
            }
        </ul>
    </div>
</div>

BanHangDienTu/Views/SanPham/ThanhToan.cshtml
@model BanHangDienTu.Models.khachhang

@{
    ViewBag.Title = "ThanhToan";
    Layout = "~/Views/Shared/_LayoutCustomize.cshtml";
}

<!-- Start All Title Box -->
<div class="all-title-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Checkout</h2>
                <ul class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#">Shop</a></li>
                    <li class="breadcrumb-item active">Checkout</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End All Title Box -->
<!-- Start Cart  -->
<div class="cart-box-main">
    <div class="container">
        <@using (Html.BeginForm("XacNhanThanhToan", "SanPham", FormMethod.Post, new { @class = "" }))
        {
            @Html.AntiForgeryToken()
            <div class="row">

                <div class="col-sm-6 col-lg-6 mb-3">
                    <div class="checkout-address">
                        <div class="title-left">
                            <h3>Thông tin nhận hàng</h3>
                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName">Tên người nhận *</label>
                                <input type="text" class="form-control" name="phieugiaohang_tennguoinhan" id="tennguoinhan" placeholder="" value="@Model.khachhang_ten" required>
                                <div class="invalid-feedback"> Valid first name is required. </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName">Số điện thoại *</label>
                                <input type="number" class="form-control" name="phieugiaohang_sdtnguoinhan" id="sdt" placeholder="" value="@Model.khachhang_sdt" required>
                                <div class="invalid-feedback"> Valid Phone Number is required. </div>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="address">Địa chỉ *</label>
                            <input type="text" class="form-control" name="phieugiaohang_diachinguoinhan" id="diachi" placeholder="" value="@Model.khachhang_diachi" required>
                            <div class="invalid-feedback"> Please enter your shipping address. </div>
                        </div>

                        <hr class="mb-4">

                        <div class="title-left">
                            <h3>Phương thức thanh toán</h3>
                        </div>
                        <div class="d-block my-3">
                            <div class="custom-control custom-radio">
                                <input id="credit" name="paymentMethod" type="radio" class="custom-control-input" checked required>
                                <label class="custom-control-label" for="credit">Thanh toán khi nhận hàng</label>
                            </div>

                        </div>
                        <hr class="mb-4">

                    </div>
                </div>
                <div class="col-sm-6 col-lg-6 mb-3">
                    <div class="row">
                        <div class="col-md-12 col-lg-12">

                        </div>
                        <div class="col-md-12 col-lg-12">
                            <div class="odr-box">
                                <div class="title-left">
                                    <a data-toggle="collapse" href="#formRegister" role="button" aria-expanded="false"><h3>Sản phẩm đã chọn <i style="font-size: 12px; color:blue">(Nhấn vào đây để xem chi tiết)</i></h3></a>
                                </div>

                                <div class="mt-3 collapse review-form-box" id="formRegister">
                                    <div class="rounded p-2 bg-light" style="overflow-y: hidden; overflow-y: auto; width: auto; height: 300px;">
                                        @{ int tongtien = 0; }
                                        @foreach (var item in ViewBag.SanPham)
                                        {
                                            <div class="media mb-2 border-bottom">
                                                <div class="media-body">
                                                    <a href="detail.html"> @item.sanpham.sanpham_ten</a>
                                                    <div class="small text-muted">Giá: @String.Format("{0:0,0}", item.sanpham.sanpham_dongia) VNĐ<span class="mx-2">|</span> Số lượng: @item.giohang_soluong <span class="mx-2">|</span> Thành tiền: @String.Format("{0:0,0}", item.sanpham.sanpham_dongia * item.giohang_soluong) VNĐ</div>
                                                </div>
                                            </div>
                                            <p class="hide">@(tongtien += (item.sanpham.sanpham_dongia * item.giohang_soluong))</p>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12 col-lg-12">
                            <div class="order-box">
                                <div class="title-left">
                                    <h3>Hóa đơn</h3>
                                </div>
                                <div class="d-flex">
                                    <div class="font-weight-bold">Chi tiết</div>
                                    <div class="ml-auto font-weight-bold">Tổng</div>
                                </div>
                                <hr class="my-1">
                                <div class="d-flex">
                                    <h4>Thành tiền</h4>
                                    <div class="ml-auto font-weight-bold"> @String.Format("{0:0,0}", tongtien) VNĐ</div>
                                </div>
                                <div class="d-flex">
                                    <h4>Khuyến mãi</h4>
                                    <div class="ml-auto font-weight-bold"> 0 </div>
                                </div>
                                <hr class="my-1">

                                <div class="d-flex">
                                    <h4>Phí vận chuyển</h4>
                                    <div class="ml-auto font-weight-bold"> Free </div>
                                </div>
                                <hr>
                                <div class="d-flex gr-total">
                                    <h5>Tổng tiền</h5>
                                    <div class="ml-auto h5"> @String.Format("{0:0,0}", tongtien) VNĐ</div>
                                </div>
                                <hr>
                            </div>
                        </div>
                        <div class="col-12 d-flex shopping-box"> <button type="submit"  class="ml-auto btn hvr-hover" style="color:white">Đặt hàng</button> </div>
                    </div>
                </div>


            </div>
        }
    </div>
</div>
<!-- End Cart -->
<!--<script>
    function ThanhToan() {

        var phieugiaohang_tennguoinhan = $('#tennguoinhan').val();
        let phieugiaohang_sdtnguoinhan = Number($('#sdt').val());
        //var email = $('#email').val();
        var phieugiaohang_diachinguoinhan = $('#diachi').val();
        window.location = "/SanPham/XacNhanThanhToan/" + phieugiaohang_tennguoinhan + "?phieugiaohang_sdtnguoinhan=" + phieugiaohang_sdtnguoinhan + "&phieugiaohang_diachinguoinhan=" + phieugiaohang_diachinguoinhan;
    }
</script>--->